import type { DnaProfile } from "./useAnalyze";
import type { SavedProfile } from "./profileStore";

/** Blend two profiles — pick the best from each. Takes color from A, rest from B as fallback. */
export function hybridizeProfiles(a: DnaProfile, b: DnaProfile, weights?: { a: number }): DnaProfile {
  const wa = weights?.a ?? 0.5;
  const wb = 1 - wa;

  // Colors: interleave both palettes, keep unique by name
  const paletteMap = new Map<string, { name: string; hex: string; role: "bg" | "surface" | "text" | "muted" | "accent" | "accent-2" }>();
  for (const c of a.palette) paletteMap.set(c.name, c);
  for (const c of b.palette) if (!paletteMap.has(c.name)) paletteMap.set(c.name, c);

  // Mood: union with A's moods first
  const moodSet = new Set<string>();
  for (const m of a.mood) moodSet.add(m);
  for (const m of b.mood) moodSet.add(m);

  // Typography: prefer A for display, B for body if different
  const typography = {
    display: wa >= 0.5 ? a.typography.display : b.typography.display,
    body: wb >= 0.5 ? b.typography.body : a.typography.body,
    scale: a.typography.scale.length >= b.typography.scale.length ? a.typography.scale : b.typography.scale,
  };

  return {
    mood: Array.from(moodSet),
    palette: Array.from(paletteMap.values()),
    typography,
    spacing: wa >= 0.5 ? a.spacing : b.spacing,
    radius: wa >= 0.5 ? a.radius : b.radius,
    effects: wa >= 0.5 ? a.effects : b.effects,
    motion: wa >= 0.5 ? a.motion : b.motion,
    confidence: Math.round((a.confidence * wa + b.confidence * wb) * 100) / 100,
  };
}

export type DiffResult = {
  palette: { name: string; a: string; b: string; same: boolean }[];
  mood: { added: string[]; removed: string[]; common: string[] };
  typography: { display: { a: string; b: string; same: boolean }; body: { a: string; b: string; same: boolean } };
  spacing: { a: number; b: number; same: boolean };
  motion: { a: string; b: string; same: boolean };
};

/** Diff two DNA profiles dimension by dimension. */
export function diffProfiles(a: DnaProfile, b: DnaProfile): DiffResult {
  // Palette diff
  const allNames = new Set([...a.palette.map((c) => c.name), ...b.palette.map((c) => c.name)]);
  const palette = Array.from(allNames).map((name) => {
    const ca = a.palette.find((c) => c.name === name);
    const cb = b.palette.find((c) => c.name === name);
    return {
      name,
      a: ca?.hex ?? "—",
      b: cb?.hex ?? "—",
      same: ca?.hex === cb?.hex,
    };
  });

  // Mood diff
  const setA = new Set(a.mood);
  const setB = new Set(b.mood);
  const mood = {
    added: b.mood.filter((m) => !setA.has(m)),
    removed: a.mood.filter((m) => !setB.has(m)),
    common: a.mood.filter((m) => setB.has(m)),
  };

  return {
    palette,
    mood,
    typography: {
      display: { a: a.typography.display, b: b.typography.display, same: a.typography.display === b.typography.display },
      body: { a: a.typography.body, b: b.typography.body, same: a.typography.body === b.typography.body },
    },
    spacing: { a: a.spacing.base, b: b.spacing.base, same: a.spacing.base === b.spacing.base },
    motion: { a: `${a.motion.ease} ${a.motion.duration_ms}ms`, b: `${b.motion.ease} ${b.motion.duration_ms}ms`, same: a.motion.ease === b.motion.ease && a.motion.duration_ms === b.motion.duration_ms },
  };
}

/** Generate a unique plain-text summary of a profile for sharing */
export function summarizeProfile(p: SavedProfile): string {
  const prof = p.profile;
  const colors = prof.palette.map((c) => `${c.name}: ${c.hex}`).join(" · ");
  return [
    `NOTEPADIFY · ${p.label}`,
    `📅 ${new Date(p.analyzedAt).toLocaleDateString()}`,
    `🎯 ${Math.round(prof.confidence * 100)}% confidence`,
    ``,
    `🎨 Colors: ${colors}`,
    `🔤 Display: ${prof.typography.display} · Body: ${prof.typography.body}`,
    `📏 Spacing base: ${prof.spacing.base}px · Scale: ${prof.spacing.scale.join(", ")}`,
    `✨ Effects: ${[prof.effects.blur, prof.effects.shadow, prof.effects.noise ? "noise" : "", prof.effects.grain ? "grain" : ""].filter(Boolean).join(", ")}`,
    `🎭 Mood: ${prof.mood.join(", ")}`,
    `🎬 Motion: ${prof.motion.ease} · ${prof.motion.duration_ms}ms`,
    ``,
    `— Generated by NOTEPADIFY`,
  ].join("\n");
}
